Cookie
idearium/idearium-lib pull request #153
Opened 2021-09-13 03:02 UTC by allanchau

This PR adds a cookie library.

## Related PRs

- Link to the related PR.

## Verification and testing

### Testing

- [ ] Check the tests.
- [ ] Test via the related PR.

2021-09-16 00:41 UTC, smebberson requested changes
@allanchau, looking good bit a few things to add here.

2021-09-16 00:41 UTC, smebberson commented on packages/cookie/tests/index.test.js
> +    console.log('serialized', serialized, typeof serialized);
@allanchau, can this be removed?

2021-09-16 00:41 UTC, smebberson commented on docusaurus/docs/cookie.md
> +await create({
@allanchau, why is `await` here? There are no promises involved?

2021-09-16 00:41 UTC, smebberson commented on docusaurus/docs/cookie.md
> +const cookie = await find({
@allanchau, same thing here regarding `await`?

2021-09-16 00:41 UTC, smebberson commented on docusaurus/docs/cookie.md
> +The create function uses the [cookie](https://www.npmjs.com/package/cookie#options-1) library in the background and can accept any `serialize` options listed there.
Below this, could you please do a little more complex example and set `httpOnly` and `secure` perhaps?

2021-09-16 00:41 UTC, smebberson commented on docusaurus/docs/cookie.md
> +The create function uses the [cookie](https://www.npmjs.com/package/cookie#options-1) library in the background and can accept any `serialize` options listed there.
Also, I think a more complete example in some middleware using `res.set('set-cookie', cookieStr);` might be good.

2021-09-16 04:14 UTC, allanchau commented
@smebberson I've updated this now

2021-09-20 01:57 UTC, smebberson approved these changes
@allanchau, looks good, please launch.

2021-09-20 04:35 UTC, merged