Added @idearium/log/multi
idearium/idearium-lib pull request #347
Opened 2023-03-06 00:28 UTC by smebberson

This PR adds `@idearium/log/multi` to make logging data dynamic based on `LOG_LEVEL`.

## Test

- [ ] Review the code.
- [ ] Review the logs.
- [ ] Ensure the tests and passing and complete enough.

## Deployment

- [ ] Version bump.

2023-03-15 23:48 UTC, allanchau requested changes
@smebberson Small change needed here, otherwise looks good to me

2023-03-15 23:48 UTC, allanchau commented on packages/log/multi.js
> +module.exports = (options = {}) => {
Can you please turn this into
```js
const log = (options = {}) => {
...
};

module.exports = log;
```

2023-03-19 23:26 UTC, smebberson commented on packages/log/multi.js
> +module.exports = (options = {}) => {
@allanchau, I renamed this.

2023-03-19 23:26 UTC, smebberson commented
@allanchau, are you okay for me to release now?

2023-03-19 23:27 UTC, allanchau approved these changes

2023-03-19 23:28 UTC, allanchau commented
@smebberson Yep all good now

2023-03-20 00:30 UTC, merged