reduce logging
idearium/idearium-lib pull request #374
Opened 2024-12-13 00:24 UTC by allanchau

Provide a brief summary of your PR...

## Tasks

- Link to the task in notion.

## Related PRs

- Link to the related PR.

## Notes

- Any additional notes you think will be useful.

## Verification and testing

**If there is both a problem and a solution, these steps should document how to demonstrate the problem that is being solved. If there is no problem (it's just a feature) you can remove the _Recreate_ section below.**

### Verification

These are the steps to demonstrate the problem being solved:

- [ ] A list of steps to demonstrate the problem.

### Testing

These are the steps to demonstrate the solution being solved; they typically include steps to update the repository to a new state containing the code that fixes the problem.

- [ ] A list of steps to demonstrate the problem.

## Deployment

- [ ] Post deployment steps (scripts to be run) and testing.
- [ ] Verify all [testing](../tree/master/docs/testing.md) steps.

2024-12-15 23:19 UTC, smebberson requested changes
@allanchau, mostly good, just a couple of changes.

2024-12-15 23:19 UTC, smebberson commented on common/mq/publisher.js
> +        .catch((err) => log.warn({ err, type }, 'Could not publish message'));
This is serious enough to remain at error isn't it?

```suggestion
        .catch((err) => log.error({ err, type }, 'Could not publish message'));
```

2024-12-15 23:19 UTC, smebberson commented on common/mq/publisher.js
> +                trace: { data },
@allanchau, this is good, but I think it should be at debug.
```suggestion
                debug: { data },
```

2024-12-16 23:36 UTC, allanchau commented
@smebberson I've updated these now

2024-12-18 23:46 UTC, smebberson approved these changes
@allanchau, this code looks good.

2025-01-05 23:36 UTC, merged